name: .NET Android

on:
  workflow_dispatch:
    inputs:
      verbosity:
        description: 'Verbosity'
        required: false
        default: 'minimal'
        type: choice
        options:
          - quiet
          - minimal
          - normal
          - detailed
      configuration:
        description: 'Verbosity'
        required: false
        default: 'minimal'
        type: choice
        options:
          - Debug
          - Release

jobs:

  build:
    runs-on: macos-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Project_Folder: DotNetAndroid.BraintreeDropInQs

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.406

    - name: Install Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
        java-package: jdk # optional (jdk or jre) - defaults to jdk
        
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Install .NET Android workload
      run: dotnet workload install android

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: |
        cd $Project_Folder
        dotnet clean -c $Configuration
      env:
        Configuration: ${{ inputs.configuration }} 

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: |
        cd $Project_Folder
        dotnet build -c $Configuration -v $Verbosity
      env:
        Configuration: ${{ inputs.configuration }} 
        Verbosity: ${{ inputs.verbosity }} 
